version: '3.8'

services:
  api-node:
    container_name: api-jest
    image: api-jest
    ports: 
      - "3333:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api-express
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api-express
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/datadocker
volumes:
  pgdata:
