name: Run E2E Tests

on:
  push:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      api-pg:
        image: bitnami/postgresql:latest
        env:
          POSTGRESQL_USERNAME: admim
          POSTGRESQL_PASSWORD: password123
          POSTGRESQL_DATABASE: apiexpress
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://admim:password123@localhost:5432/apiexpress?schema=public"